<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.github.meggermo.maven</groupId>
    <artifactId>maven.pom.root</artifactId>
    <version>2.0.0</version>
  </parent>
  <groupId>nl.meg</groupId>
  <artifactId>jcr-ops</artifactId>
  <version>1.0.5-SNAPSHOT</version>
  <packaging>bundle</packaging>
  <name>${project.artifactId}</name>
  <description>Functional immutable operations on the Content repository API for Java.</description>
  <url>https://${github.host}/${project.artifactId}</url>
  <inceptionYear>2014</inceptionYear>
  <organization>
    <name>${github.account.name}</name>
    <url>https://${github.host}</url>
  </organization>
  <licenses>
    <license>
      <name>MIT License</name>
      <url>https://raw.githubusercontent.com/${github.account.name}/jcr-ops/master/LICENSE.txt</url>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>${github.account.name}</id>
      <name>Michiel Eggermont</name>
      <email>michiel.eggermont@gmail.com</email>
      <url>https://${github.host}</url>
    </developer>
  </developers>
  <scm>
    <connection>scm:https://${github.host}/${project.artifactId}</connection>
    <developerConnection>scm:git:ssh://git@${github.host}/jcr-ops</developerConnection>
    <url>https://${github.host}/${project.artifactId}</url>
  </scm>
  <issueManagement>
    <system>github</system>
    <url>https://${github.host}/jcr-ops/issues</url>
  </issueManagement>
  <properties>
    <maven.compiler.release>21</maven.compiler.release>
    <github.account.name>${project.name}</github.account.name>
    <!-- Library versions -->
    <jcr.version>2.0</jcr.version>
    <oak-jcr.version>1.78.0</oak-jcr.version>
    <logback.version>1.5.18</logback.version>
    <maven-bundle-plugin.version>6.0.0</maven-bundle-plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>javax.jcr</groupId>
        <artifactId>jcr</artifactId>
        <version>${jcr.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.jackrabbit</groupId>
        <artifactId>oak-jcr</artifactId>
        <version>${oak-jcr.version}</version>
      </dependency>
      <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-classic</artifactId>
        <version>${logback.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>javax.jcr</groupId>
      <artifactId>jcr</artifactId>
    </dependency>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.annotation.versioning</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.jackrabbit</groupId>
      <artifactId>oak-jcr</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <repositories>
    <repository>
      <releases>
        <enabled>true</enabled>
        <checksumPolicy>ignore</checksumPolicy>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>github</id>
      <name>Github repository for pom files only</name>
      <url>https://raw.githubusercontent.com/meggermo/maven.pom.root/master</url>
    </repository>
  </repositories>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>${maven-bundle-plugin.version}</version>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <Export-Package>nl.meg.jcr.*;provide:=true</Export-Package>
          </instructions>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
